name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configurando python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - name: Creating and activate virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          python --version
          pip install dvc==2.10.2
          pip install fsspec==2022.11.0
          pip install dvc[gs]
          pip install -r requirement_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
          pytest tests.py
